/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import configuration.SpringConfig;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

import log.ArquivoLog;
import services.ProdutoService;

public class TelaInicial extends javax.swing.JFrame {
    

    /**
     * Creates new form Main
     */
    public TelaInicial() {
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cinemax_icon = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuItemProduto = new javax.swing.JMenuItem();
        menuItemGenero = new javax.swing.JMenuItem();
        menuItemDiretor = new javax.swing.JMenuItem();
        menuItemSala = new javax.swing.JMenuItem();
        menuItemFaixaEtaria = new javax.swing.JMenuItem();
        menuItemTipoProduto = new javax.swing.JMenuItem();
        menuItemPermissoes = new javax.swing.JMenuItem();
        menuItemArquivarAuditoria = new javax.swing.JMenuItem();
        menuItemConsultaCNPJ = new javax.swing.JMenuItem();
        menuItemExportarProdutos = new javax.swing.JMenuItem();
        menuItemBackup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinemax");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cinemax_icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexa\\Documents\\GitHub\\cinemax\\src\\main\\resources\\images\\cinemax_icon.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cinemax_icon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cinemax_icon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuCadastro.setText("Cadastros");

        menuItemProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menuItemProduto.setText("Produtos");
        menuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemProduto);

        menuItemGenero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        menuItemGenero.setText("Gêneros");
        menuItemGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGeneroActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemGenero);

        menuItemDiretor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menuItemDiretor.setText("Diretores");
        menuItemDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDiretorActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemDiretor);

        menuItemSala.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuItemSala.setText("Salas");
        menuItemSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemSala);

        menuItemFaixaEtaria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        menuItemFaixaEtaria.setText("Faixas Etárias");
        menuItemFaixaEtaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFaixaEtariaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemFaixaEtaria);

        menuItemTipoProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuItemTipoProduto.setText("Cargos");
        menuItemTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTipoProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemTipoProduto);

        menuItemPermissoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        menuItemPermissoes.setText("Permissões");
        menuItemPermissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPermissoesActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemPermissoes);

        menuItemArquivarAuditoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        menuItemArquivarAuditoria.setText("Arquivar Auditoria");
        menuItemArquivarAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemArquivarAuditoriaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemArquivarAuditoria);

        menuItemConsultaCNPJ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        menuItemConsultaCNPJ.setText("Consulta CNPJ");
        menuItemConsultaCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaCNPJActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemConsultaCNPJ);

        menuItemExportarProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        menuItemExportarProdutos.setText("Exportar Produtos");
        menuItemExportarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExportarProdutosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemExportarProdutos);

        menuItemBackup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        menuItemBackup.setText("Backup");
        menuItemBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBackupActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemBackup);

        jMenuBar1.add(menuCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProdutoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProduto(new TelaInicial(), true).setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemProdutoActionPerformed

    private void menuItemTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTipoProdutoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCargo(new TelaInicial(), true).setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemTipoProdutoActionPerformed

    private void menuItemGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGeneroActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenero(new TelaInicial(), true).setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemGeneroActionPerformed

    private void menuItemDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDiretorActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDiretor(new TelaInicial(), true).setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemDiretorActionPerformed

    private void menuItemSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSala(new TelaInicial(), true).setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemSalaActionPerformed

    private void menuItemFaixaEtariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFaixaEtariaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFaixaEtaria(new TelaInicial(), true).setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemFaixaEtariaActionPerformed

    private void menuItemAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAuditoriaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAuditoria(new TelaInicial(), true).setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemAuditoriaActionPerformed

    private void menuItemPermissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPermissoesActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                 new TelaPermissao(new TelaInicial(), true).setVisible(true);
             }
         });
    }//GEN-LAST:event_menuItemPermissoesActionPerformed

    private void menuItemArquivarAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemArquivarAuditoriaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new TelaArquivarAuditoria(new TelaInicial(), true).setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemArquivarAuditoriaActionPerformed

    private void menuItemConsultaCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaCNPJActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new TelaProdutoFornecedor(new TelaInicial(), true).setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemConsultaCNPJActionPerformed

    private void menuItemExportarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExportarProdutosActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new TelaExportarProduto(new TelaInicial(), true).setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemExportarProdutosActionPerformed

    private void menuItemBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBackupActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new TelaBackup(new TelaInicial(), true).setVisible(true);
            }
        });
    }//GEN-LAST:event_menuItemBackupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new ArquivoLog("Erros 1");

                TelaInicial frame = new TelaInicial();
                
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cinemax_icon;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuItemArquivarAuditoria;
    private javax.swing.JMenuItem menuItemBackup;
    private javax.swing.JMenuItem menuItemConsultaCNPJ;
    private javax.swing.JMenuItem menuItemDiretor;
    private javax.swing.JMenuItem menuItemExportarProdutos;
    private javax.swing.JMenuItem menuItemFaixaEtaria;
    private javax.swing.JMenuItem menuItemGenero;
    private javax.swing.JMenuItem menuItemPermissoes;
    private javax.swing.JMenuItem menuItemProduto;
    private javax.swing.JMenuItem menuItemSala;
    private javax.swing.JMenuItem menuItemTipoProduto;
    // End of variables declaration//GEN-END:variables
}
